0~name: dyslexia-chinese
channels:
  - defaults
  - conda-forge
  - pytorch
  - r
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - tqdm
  - notebook
  - matplotlib
  - spacy=3.2.2
  - pylint=2.4.4
  - pip
  - pip:
    - seaborn
    - ipdb
    - rpy2
    - tzlocal
    - simplegeneric
    - transformers
    - https://github.com/kpu/kenlm/archive/master.zip1
    - https://github.com/explosion/spacy-models/releases/download/zh_core_web_trf-3.2.0/zh_core_web_trf-3.2.0-py3-none-any.whl
